[project]
name = "nomtransformerocr"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pytorch-lightning>=2.6.1",
    "torchvision>=0.25.0",
]
